[project]
name = "predict-ligue1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "flask>=3.1.2",
    "ipykernel>=7.2.0",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "streamlit>=1.19.0",
]
